# Kentucky

[20200623]
date = 2020-06-23
name = "Presidential Primary"
original_date = 2020-06-23

[20200623.absentee]
postmarked_by = 2020-06-23
received_by = 2020-06-27T18:00:00
sources = ["https://elect.ky.gov/SiteAssets/Pages/default/Primary%20Timeline.pdf",
           "https://elect.ky.gov/SiteAssets/Pages/default/SBE%20Covid19%20Emergency%20Regulation.pdf"]

[20200623.absentee.application]
online_by = 2020-06-15T23:59:59
already_registered = true

[20200623.poll]
in_person_by = 2020-06-23

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
online_by = 2020-10-05T16:00:00
received_by = 2020-10-05T16:00:00
in_person_by = 2020-10-05T16:00:00
sources = ["https://elect.ky.gov/Resources/Documents/2020%20Election%20Calendar%20with%20Primary%20Postponement.pdf"]

[20201103.absentee.application]
received_by = 2020-10-27
sources = ["https://elect.ky.gov/Resources/Documents/2020%20Election%20Calendar%20with%20Primary%20Postponement.pdf"]

[20201103.absentee]
received_by = 2020-11-03T18:00:00
sources = ["https://elect.ky.gov/Resources/Documents/2020%20Election%20Calendar%20with%20Primary%20Postponement.pdf"]

[20201103.poll.early]
in_person_start = 2020-10-13
in_person_by = 2020-11-02
sources = ["https://vrsws.sos.ky.gov/abrweb/"]

[20201103.poll]
in_person_start = 2020-11-03T06:00:00
in_person_by = 2020-11-03T18:00:00
received_by = 2020-11-03T18:00:00
sources = ["https://elect.ky.gov/Resources/Documents/2020%20Election%20Calendar%20with%20Primary%20Postponement.pdf"]
