[20200811]
date = 2020-08-11
name = "Presidential Primary"
original_date = 2020-08-11

[20200811.registration]
postmarked_by = 2020-08-06
received_by = 2020-08-06
online_by = 2020-08-06
in_person_start = 2020-08-11T06:00:00 # available at a designated EDR location in each town
in_person_by = 2020-08-11T20:00:00 # available at a designated EDR location in each town
sources = [
    "https://portal.ct.gov/-/media/SOTS/ElectionServices/Calendars/2020Election/August-11-Updated-Presidential-Preference-Primary.pdf",
    "https://portal.ct.gov/-/media/SOTS/ElectionServices/Calendars/2020Election/2020-Calendar.pdf",
    "https://portal.ct.gov/SOTS/Election-Services/Election-Day-Registration-2013/Election-Day-Registration",
    "https://portal.ct.gov/SOTS/Election-Services/Registration-Deadlines/Registration-Deadlines"
]

[20200811.absentee.application]
received_by = 2020-08-10

[20200811.absentee]
fax_by = 2020-08-11T20:00:00 # you must still mail it as well
received_by = 2020-08-11T20:00:00
sources = [
    "https://portal.ct.gov/-/media/SOTS/ElectionServices/Calendars/2020Election/2020-Calendar.pdf",
    "https://portal.ct.gov/SOTS/Election-Services/FAQ/FAQ---Absentee-Balloting"
]


[20200811.poll]
in_person_start = 2020-08-11T06:00:00
in_person_by = 2020-08-11T20:00:00
sources = [
    "https://portal.ct.gov/-/media/SOTS/ElectionServices/Calendars/2020Election/August-11-Updated-Presidential-Preference-Primary.pdf"
]

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
postmarked_by = 2020-10-27
received_by = 2020-10-27
on_line_by = 2020-10-27
in_person_start = 2020-11-03T06:00:00 # available at a designated EDR location in each town
in_person_by = 2020-11-03T20:00:00 # available at a designated EDR location in each town
sources = [
    "https://portal.ct.gov/-/media/SOTS/ElectionServices/Calendars/2020Election/2020-Calendar.pdf",
    "https://portal.ct.gov/SOTS/Election-Services/Election-Day-Registration-2013/Election-Day-Registration"
]

[20201103.absentee.application]
received_by = 2020-08-10

[20201103.absentee]
fax_by = 2020-11-03T20:00:00 # you must still mail it as well
received_by = 2020-11-03T20:00:00
sources = [
    "https://portal.ct.gov/-/media/SOTS/ElectionServices/Calendars/2020Election/2020-Calendar.pdf",
    "https://portal.ct.gov/SOTS/Election-Services/FAQ/FAQ---Absentee-Balloting"
]

[20201103.poll]
in_person_start = 2020-11-03T06:00:00
in_person_by = 2020-11-03T20:00:00
sources = [
    "https://portal.ct.gov/-/media/SOTS/ElectionServices/Calendars/2020Election/2020-Calendar.pdf"
]
