name = "Tennessee"
fips_code = 47
postal_code = "TN"
homepage = "https://sos.tn.gov/elections"
registration_info = "https://ovr.govote.tn.gov/"
absentee_info = "https://sos.tn.gov/products/elections/how-do-i-request-absentee-ballot"
military_overseas_info = "https://sos.tn.gov/products/elections/how-do-i-request-absentee-ballot-if-i-am-military-or-overseas"
