name = "New York"
fips_code = 36
postal_code = "NY"
demonym = "New Yorker"
homepage = "https://www.elections.ny.gov/"
registration_info = "https://www.elections.ny.gov/VotingRegister.html"
absentee_info = "https://www.elections.ny.gov/VotingAbsentee.html"
military_overseas_info = "https://www.elections.ny.gov/VotingMilitaryFed.html"

change_of_address_lead_time = 20 # days

[[link]]
url = "https://www.sos.ms.gov/content/documents/elections/2020%20Website%20Calendar.pdf"
description = "2020 Calendar PDF"
