name = "Maine"
fips_code = 23
postal_code = "ME"
homepage = "http://www.maine.gov/sos/cec/elec/"
registration_info = "http://www.maine.gov/sos/cec/elec/voter-info/votreg.html"
absentee_info = "https://www.maine.gov/sos/cec/elec/voter-info/absent.html"
military_overseas_info = "https://www.maine.gov/sos/cec/elec/voter-info/move-act.html"
demonym = "Mainer"
