name = "Alaska"
fips_code = 2
postal_code = "AK"
homepage = "http://www.elections.alaska.gov/"
registration_info = "https://voterregistration.alaska.gov/"
absentee_info = "http://www.elections.alaska.gov/Core/AKVoteEarly.php"
military_overseas_info = "http://www.elections.alaska.gov/Core/MOSCselection.php"
demonym = "Alaskan"

[registration] 
postmarked_by_lead_time = 30 #days
presidential_received_by_lead_time = 10 #days

[absentee.application]
received_by_lead_time = 10 #days

[voting.rules]
early_voting_starts = 15 #days
#early_voting_ends = 0 #days 

change_of_address_lead_time = 30 # days
