[20200317]
date = 2020-03-17
name = "Congressional & Presidential Primary"
original_date = 2020-03-17

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
in_person_by = 2020-11-03 # Grace Period Registration
online_by = 2020-10-18T23:59:00 
sources = [
  "https://ova.elections.il.gov/",
  "https://www.elections.il.gov/Redirect.aspx?URL=N89sl87jypsxPw6B0KYKSrLBzH9l9TRC0CNjTy2S7HpqNip9yHUt5hhL4RVvuMtYvWwIKITQhmqHSXoDyzhUW5YuIsL2zOlwRZLxPLK6JVcpMZp3ZZO%2bl%2fusTQjTe6jlDPWHzxuDhc4BFAM4KO1RGZ9bmj%2bjIacouz2KG%2bDDT9f%2blqFo5%2bmEtY4Ysrl4d7Rd",
] 

[20201103.absentee.application]
in_person_by = 2020-11-02
received_by = 2020-10-29
sources = ["https://www.elections.il.gov/ElectionOperations/VotingByMail.aspx"]

[20201103.absentee]
postmarked_by = 2020-11-03
received_by = 2020-11-17
sources = ["https://www.elections.il.gov/DocDisplay.aspx?Doc=Downloads/ElectionOperations/PDF/VoteByMail.pdf"]

[20201103.poll.early]
in_person_by = 2020-11-02
sources = ["https://www.elections.il.gov/DocDisplay.aspx?Doc=/Downloads/ElectionOperations/PDF/EarlyVoting.pdf&MID=10"]

[20201103.poll]
2020-11-03T06:00:00
2020-11-03T19:00:00
sources = ["https://www.elections.il.gov/ElectionOperations/ElectionDayVoting.aspx"]
