[20200519]
date = 2020-06-02
name = "Congressional Primary"
original_date = 2020-05-19
results = "https://www.livevoterturnout.com/Idaho/LiveResults/1/en/Index_112.html"

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
online_by = 2020-10-09T23:59:59
postmarked_by = 2020-10-09T17:00:00
sources = ["https://idahovotes.gov/media/voter_registration.pdf", "https://sos.idaho.gov/election-calendars/#2020"]

[20201103.absentee.application]
inperson_by = 2020-10-30T17:00:00
online_by = 2020-10-23T20:00:00
received_by = 2020-10-23T20:00:00
sources = [
  "https://elections.sos.idaho.gov/ElectionLink/ElectionLink/BeginAbsenteeRequest.aspx",
  "https://idahovotes.gov/absentee-voter-information/",
]

[20201103.absentee]
received_by = 2020-11-03T20:00:00
sources = ["https://sos.idaho.gov/election-calendars/#2020"]

[20201103.poll.early]
in_person_by = 2020-10-30T17:00:00 # Not in all counties
in_person_start = 2020-10-19 # Not in all counties
sources = ["https://sos.idaho.gov/election-calendars/#2020"] 

[20201103.poll]
in_person_by = 2020-11-03T20:00:00
in_person_start = 2020-11-03T08:00:00
