[20200303]
date = 2020-03-03
name = "Presidential Primary"
original_date = 2020-03-03

[20200811]
date = 2020-08-11
name = "Congresssional Primary"
original_date = 2020-08-11

[20200811.registration]
online_by = 2020-07-21T23:59:00
received_by = 2020-07-21T17:00:00
in_person_by = 2020-08-11T20:00:00
sources = [
    "https://www.sos.state.mn.us/elections-voting/election-day-voting/",
    "https://www.sos.state.mn.us/elections-voting/election-day-voting/voting-hours/",
    "https://www.sos.state.mn.us/elections-voting/register-to-vote/registration-faqs/"
]

[20200811.absentee.application]
online_by = 2020-08-10 # Legally this is true, but you'll never receive it.
received_by = 2020-08-10 # Legally this is true, but you'll never receive it.
fax_by =  2020-08-10 # Legally this is true, but you'll never receive it.
email_by =  2020-08-10 # Legally this is true, but you'll never receive it.
sources = [
    "https://www.sos.state.mn.us/elections-voting/other-ways-to-vote/vote-early-by-mail/",
    "https://mnvotes.sos.state.mn.us/ABRegistration/ABRegistrationStep1.aspx"
]

[20200811.absentee]
received_start = 2020-06-26
postmarked_by = 2020-08-10
receive_by = 2020-08-12 # See "received by your county by the day before the county canvass"
in_person_start = 2020-06-26
in_person_by = 2020-08-11T15:00:00
sources = [
    "https://www.sos.state.mn.us/election-administration-campaigns/elections-calendar/",
    "https://www.sos.state.mn.us/elections-voting/other-ways-to-vote/",
    "https://www.sos.state.mn.us/elections-voting/other-ways-to-vote/vote-early-by-mail/"
]

[20200811.poll]
in_person_start = 2020-08-11T07:00:00
in_person_by = 2020-08-11T20:00:00
sources = [
    "https://www.sos.state.mn.us/election-administration-campaigns/elections-calendar/",
    "https://www.sos.state.mn.us/elections-voting/election-day-voting/voting-hours/",
]

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
online_by = 2020-10-13T23:59:00
received_by = 2020-10-13T17:00:00
in_person_by = 2020-11-03T20:00:00
sources = [
    "https://www.sos.state.mn.us/elections-voting/election-day-voting/",
    "https://www.sos.state.mn.us/elections-voting/election-day-voting/voting-hours/",
    "https://www.sos.state.mn.us/elections-voting/register-to-vote/registration-faqs/"
]

[20201103.absentee.application]
online_by = 2020-11-02 # Legally this is true, but you'll never receive it.
received_by = 2020-11-02 # Legally this is true, but you'll never receive it.
fax_by =  2020-11-02 # Legally this is true, but you'll never receive it.
email_by =  2020-11-02 # Legally this is true, but you'll never receive it.
sources = [
    "https://www.sos.state.mn.us/elections-voting/other-ways-to-vote/vote-early-by-mail/",
    "https://mnvotes.sos.state.mn.us/ABRegistration/ABRegistrationStep1.aspx"
]

[20201103.absentee]
receive_start = 2020-09-18
receive_by = 2020-11-02
in_person_start = 2020-09-18T07:00:00
in_person_by = 2020-11-02T17:00:00
sources = [
    "https://www.sos.state.mn.us/election-administration-campaigns/elections-calendar/",
    "https://www.sos.state.mn.us/elections-voting/other-ways-to-vote/"
]

[20201103.poll]
in_person_start = 2020-11-03T07:00:00
in_person_by = 2020-11-03T20:00:00
sources = [
    "https://www.sos.state.mn.us/election-administration-campaigns/elections-calendar/",
    "https://www.sos.state.mn.us/elections-voting/election-day-voting/voting-hours/",
]
