[20200602]
date = 2020-06-02
name = "Congressional & Presidential Primary"
original_date = 2020-06-02

[20201103]
date = 2020-11-03
name = "General"
original_date = 2020-11-03

[20201103.registration]
in_person_by = 2020-10-19
online_by = 2020-10-19
received_by = 2020-10-19
sources = [
  "https://www.votespa.com/Register-to-Vote/Pages/default.aspx",
]

[20201103.absentee.application]
in_person_by = 2020-10-27T17:00:00
received_by = 2020-10-27T17:00:00
sources = ["https://www.votespa.com/Voting-in-PA/Pages/Mail-and-Absentee-Ballot.aspx"]

[20201103.absentee]
received_by = 2020-11-03T20:00:00
sources = ["https://www.votespa.com/Voting-in-PA/Pages/Mail-and-Absentee-Ballot.aspx"]

[20201103.poll]
in_person_by = 2020-11-03T20:00:00
in_person_start = 2020-11-03T07:00:00
sources = ["https://www.votespa.com/Voting-in-PA/Pages/Voting-at-a-Polling-Place.aspx"]
