[20200609]
date = 2020-06-09
name = "Presidential Primary"
original_date = 2020-06-09

[20200811]
date = 2020-08-11
name = "Congressional Primary Run-off (if needed)"
original_date = 2020-08-11

[20200811.registration]
online_by = 2020-07-13
received_by = 2020-07-13
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20200811.absentee.application]
email_by = 2020-07-28 # Padded 14 Days
received_by = 2020-07-28 # Padded 14 Days
fax_by = 2020-07-28 # Padded 14 Days
in_person_by = 2020-08-11
sources = [
  "https://sos.ga.gov/index.php/Elections/absentee_voting_in_georgia",
  "https://ballotpedia.org/Election_governance_in_Georgia#Absentee_voting",
]

[20200811.absentee]
received_by = 2020-08-11T19:00:00
sources = ["https://ballotpedia.org/Election_governance_in_Georgia#Absentee_voting"]

[20200811.poll.early]
in_person_start = 2020-07-20 # Varies or not at all in some counties
sources = [
  "https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf",
  "https://elections.sos.ga.gov/Elections/advancedVotingInfo.do"
]

[20200811.poll]
in_person_by = 2020-08-11T19:00:00
in_person_start = 2020-08-11T07:00:00
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20201201]
date = 2020-12-01
name = "General Election and Special Election Runoffs for Local and State Offices  (if needed)"
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20201201.registration]
online_by = 2020-10-05
received_by = 2020-10-05
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20201201.poll.early]
in_person_start = "As Early as Possible"
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20201201.poll]
in_person_by = 2020-12-01T19:00:00
in_person_start = 2020-12-01T07:00:00
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20201103]
date = 2020-11-03
name = "General Election and Special Election"
original_date = 2020-11-03

[20201103.registration]
online_by = 2020-10-05
received_by = 2020-10-05
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20201103.absentee.application]
email_by = 2020-10-20 # Padded 14 Days
received_by = 2020-10-20 # Padded 14 Days
fax_by = 2020-10-20 # Padded 14 Days
in_person_by = 2020-11-03
sources = [
  "https://sos.ga.gov/index.php/Elections/absentee_voting_in_georgia",
  "https://ballotpedia.org/Election_governance_in_Georgia#Absentee_voting",
]

[20201103.absentee]
received_by = 2020-11-03T19:00:00
sources = ["https://ballotpedia.org/Election_governance_in_Georgia#Absentee_voting"]

[20201103.poll.early]
in_person_start = 2020-10-12
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20201103.poll]
in_person_by = 2020-11-03T19:00:00
in_person_start = 2020-11-03T07:00:00
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20201201]
date = 2020-12-01
name = "General Election and Special Election Runoffs for Local and State Offices  (if needed)"
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20201201.registration]
online_by = 2020-10-05
received_by = 2020-10-05
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20201201.poll.early]
in_person_start = "As Early as Possible"
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20201201.poll]
in_person_by = 2020-12-01T19:00:00
in_person_start = 2020-12-01T07:00:00
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20210105]
date = 2021-01-05
name = "General Run-Off for Federal Offices (if needed)"
original_date = 2021-01-05

[20210105.registration]
online_by = 2020-12-07
received_by = 2020-12-07
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20210105.poll.early]
in_person_start = 2020-12-14
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]

[20210105.poll]
in_person_by = 2021-01-05T19:00:00
in_person_start = 2021-01-05T07:00:00
sources = ["https://sos.ga.gov/admin/files/2020%20Revised%20Short%20Calendar.pdf"]
