name = "South Carolina"
fips_code = 45
postal_code = "SC"
homepage = "https://www.scvotes.org"
registration_info = "https://info.scvotes.sc.gov/eng/ovr/start.aspx"
absentee_info = "https://www.scvotes.org/absentee-voting"
military_overseas_info = "https://www.scvotes.org/military-overseas-citizens"
demonym = "South Carolinian"

[[link]]
description = "2020 Calendar PDF"
url = "https://www.scvotes.org/sites/default/files/2020%20Election%20Calendar%20(scVOTES)%202019-08-06_0.pdf"
