name = "Ohio"
fips_code = 39
postal_code = "OH"
homepage = "https://www.sos.state.oh.us/elections/"
registration_info = "https://olvr.ohiosos.gov/"
absentee_info = "https://www.sos.state.oh.us/elections/voters/absentee-voting/"
military_overseas_info = "https://www.sos.state.oh.us/secretary-office/military/"
demonym = "Ohioan"
